=== kevinmg7/viva-el-anime/public/validacion.xsd
<?xml version="1.0"?>


<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="introduction">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="link" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="notice" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="link" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType> 
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kevinmg7/viva-el-anime/plantilla_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="public/validacion.xsd">
    <introduction >
        <title>Anime News Network - News</title>
        <link>https://www.animenewsnetwork.com/news/</link>
        <description>ANN RSS feed</description>
    </introduction>
    <notice>
        <title>Shout! Factory's TokuSHOUTsu Channel Teases Kamen Rider Kuuga</title>
        <link>http://www.animenewsnetwork.com/daily-briefs/2020-04-29/shout-factory-tokushoutsu-channel-teases-kamen-rider-kuuga/.159089</link>
        <description/>
    </notice>
    <notice>
        <title>Nikkei: Japan to Extend COVID-19 State of Emergency</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-29/nikkei-japan-to-extend-covid-19-state-of-emergency/.159100</link>
        <description>Expert meeting on Friday to discuss proposal to extend to late May or June 7</description>
    </notice>
    <notice>
        <title>Olympics Committee President: Games Will Be 'Scrapped' If Not Held in 2021</title>
        <link>http://www.animenewsnetwork.com/daily-briefs/2020-04-29/olympics-committee-president-games-will-be-scrapped-if-not-held-in-2021/.159091</link>
        <description/>
    </notice>
    <notice>
        <title>Chinese Site Administrator Sentenced for Posting Early Shonen Jump Scans</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-29/chinese-site-administrator-sentenced-for-posting-early-shonen-jump-scans/.159092</link>
        <description>Shueisha also pursues civil suit against admin of site that opened in 2013, had 400,000 unique users</description>
    </notice>
    <notice>
        <title>Oscars. Golden Globes Temporarily Change Eligibility Rules Due to COVID-19</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-29/oscars-golden-globes-temporarily-change-eligibility-rules-due-to-covid-19/.159088</link>
        <description>Both waive requirements for LA county screenings</description>
    </notice>
    <notice>
        <title>2nd Seitokai Yakuindomo Film Unveils 1st Trailer, Visual</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/2nd-seitokai-yakuindomo-film-unveils-1st-trailer-visual/.159090</link>
        <description>Film opens in Japan on July 10</description>
    </notice>
    <notice>
        <title>LiSA's Demon Slayer: Kimetsu no Yaiba Single Ranks #1 on Oricon Weekly Digital for 3rd Time</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/lisa-demon-slayer-kimetsu-no-yaiba-single-ranks-no.1-on-oricon-weekly-digital-for-3rd-time/.159087</link>
        <description>'Gurenge' opening song has 786,000 total downloads</description>
    </notice>
    <notice>
        <title>North American Anime, Manga Releases, April 26-May 2</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/north-american-anime-manga-releases-april-26-may-2/.159069</link>
        <description>&lt;cite&gt;RobiHachi&lt;/cite&gt;, &lt;cite&gt;W'z&lt;/cite&gt; anime; &lt;cite&gt;BL Metamorphosis&lt;/cite&gt;, &lt;cite&gt;The King of Fighters: A New Beginning&lt;/cite&gt; manga ship</description>
    </notice>
    <notice>
        <title>Octopath Traveler Game Launches on Stadia</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/octopath-traveler-game-launches-on-stadia/.159077</link>
        <description>RPG adds Korean patch on all platforms this summer</description>
    </notice>
    <notice>
        <title>One Piece Anime's English Dub Returns With Digital Release</title>
        <link>http://www.animenewsnetwork.com/daily-briefs/2020-04-28/one-piece-anime-english-dub-returns-with-digital-release/.159078</link>
        <description/>
    </notice>
    <notice>
        <title>Miko Mitsuki's Teito Hatsukoi Shinjū Manga Ends in 9th Volume</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/miko-mitsuki-teito-hatsukoi-shinju-manga-ends-in-9th-volume/.159051</link>
        <description>&lt;cite&gt;Honey Blood&lt;/cite&gt; creator's Taishō-era romance ends around this winter</description>
    </notice>
    <notice>
        <title>Funimation Streams Anime, Live-Action Films With Bigscreen VR Service</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/funimation-streams-anime-live-action-films-with-bigscreen-vr-service/.159055</link>
        <description>Streaming events offer &lt;cite&gt;your name.&lt;/cite&gt;, &lt;cite&gt;Akira&lt;/cite&gt;, &lt;cite&gt;My Hero Academia&lt;/cite&gt;, more in May, June</description>
    </notice>
    <notice>
        <title>Aokana - Four Rhythms Across the Blue Game Ships in West on August 21</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/aokana-four-rhythms-across-the-blue-game-ships-in-west-on-august-21/.159068</link>
        <description>Game launches digitally for PS4; physically, digitally for Switch</description>
    </notice>
    <notice>
        <title>Tokyo 7th Sisters Anime Film's Teaser Unveils Staff, Title</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/tokyo-7th-sisters-anime-film-teaser-unveils-staff-title/.159065</link>
        <description>LandQ studios animates script by idol game's chief director Shintarō Motegi</description>
    </notice>
    <notice>
        <title>Kaiju Step TV Anime Shorts With Ultraman Monsters Get 2nd Season</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/kaiju-step-tv-anime-shorts-with-ultraman-monsters-get-2nd-season/.159063</link>
        <description>&lt;cite&gt;Ultraseven&lt;/cite&gt;-inspired Ele-chan joins cast</description>
    </notice>
    <notice>
        <title>Kyoto Animation's Studio 1 Building Demolition Completed</title>
        <link>http://www.animenewsnetwork.com/daily-briefs/2020-04-28/kyoto-animation-studio-1-building-demolition-completed/.159060</link>
        <description/>
    </notice>
    <notice>
        <title>Monster Strike The Movie: Lucifer Zetsubō no Yoake Delayed Due to COVID-19</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/monster-strike-the-movie-lucifer-zetsubo-no-yoake-delayed-due-to-covid-19/.159061</link>
        <description>Film would have opened in June</description>
    </notice>
    <notice>
        <title>Yoshimi Muneyama's A3! AUTUMN Manga Ends</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/yoshimi-muneyama-a3-autumn-manga-ends/.159056</link>
        <description>Muneyama's 3rd manga based on &lt;cite&gt;A3!&lt;/cite&gt; actor-training smartphone game</description>
    </notice>
    <notice>
        <title>The God of High School Anime's English-Subtitled Trailer Reveals More Cast, Staff</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-28/the-god-of-high-school-anime-english-subtitled-trailer-reveals-more-cast-staff/.159058</link>
        <description>Anime premieres on TV in Japan in July, with worldwide debut planned</description>
    </notice>
    <notice>
        <title>ROOM CAMP Anime's New Episode Streams for 1 Day on Wednesday</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/room-camp-anime-new-episode-streams-for-1-day-on-wednesday/.159057</link>
        <description>"Sauna to Gohan to Sanrin Bike" introduces Rin's father, ships on May 27</description>
    </notice>
    <notice>
        <title>Nyx no Lantern, Sazae-san's Machiko Hasegawa Win Tezuka Osamu Cultural Prizes</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/nyx-no-lantern-sazae-san-machiko-hasegawa-win-tezuka-osamu-cultural-prizes/.159053</link>
        <description>&lt;cite&gt;Mizu wa Umi ni Mukatte Nagareru&lt;/cite&gt;, &lt;cite&gt;'Muchū sa, Kimi ni'&lt;/cite&gt; manga also win</description>
    </notice>
    <notice>
        <title>Actor Shu Wada Passes Away Due to COVID-19</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/actor-shu-wada-passes-away-due-to-covid-19/.159048</link>
        <description>Father of anime/novel writer Gen Urobuchi passed away on April 23</description>
    </notice>
    <notice>
        <title>Dragon Ball Z: Kakarot Game's Trailer Previews 'New Power Awakens' DLC</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/dragon-ball-z-kakarot-game-trailer-previews-new-power-awakens-dlc/.159050</link>
        <description>1st of 2-part DLC featuring Beerus, Whis, Super Saiyan God forms launches on Tuesday</description>
    </notice>
    <notice>
        <title>Overlord Novel Series Ends With 17th Volume</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/overlord-novel-series-ends-with-17th-volume/.159047</link>
        <description>Kugane Maruyama's series launched in 2010, inspired anime in 2015</description>
    </notice>
    <notice>
        <title>Dropout Idol Fruit Tart TV Anime Reveals Additional Cast</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/dropout-idol-fruit-tart-tv-anime-reveals-additional-cast/.159046</link>
        <description>Yōko Hikasa, Kaoru Sakura, Yū Sasahara, Takako Tanaka join cast</description>
    </notice>
    <notice>
        <title>Broccoli's Jack Jeanne Switch Game Delayed to December 3</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/broccoli-jack-jeanne-switch-game-delayed-to-december-3/.159044</link>
        <description>Game collaboration with Sui Ishida previously set for August 5 in Japan</description>
    </notice>
    <notice>
        <title>S.A's Maki Minami Ends Oshapiku Shite Kimasen ka? Manga</title>
        <link>http://www.animenewsnetwork.com/news/2020-04-27/s.a-maki-minami-ends-oshapiku-shite-kimasen-ka-manga/.159030</link>
        <description>Manga launched in 2018, centers on 4 girls who meet to eat good food</description>
    </notice>
    <notice>
        <title>Ōoku: The Inner Chambers Alternate History Manga Enters Final Arc</title>
